name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Build
      run: ci/build.sh

    - name: Store Artifact
      uses: actions/upload-artifact@v3
      with:
        name: PY_LGPIO
        path: dist/
